[package]
name = "synctl"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
base64.workspace = true
clap.workspace = true
hex.workspace = true
http.workspace = true
libc.workspace = true
p256.workspace = true
rustls-pemfile.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
socket2.workspace = true
syn-config = { path = "../syn-config" }
syn-protocol = { path = "../syn-protocol" }
toml.workspace = true
zeroize.workspace = true
