[package]
name = "syn-sim"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
hex.workspace = true
libc.workspace = true
minicbor.workspace = true
p256.workspace = true
syn-protocol = { path = "../syn-protocol" }
zeroize.workspace = true
